### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by sidrahassanpk** [samarthagarwal/woocommerce_dart#11]
Here is the the code line which is causing error:-

`subtitle: Text("Rs. " + s.data[index]["price"] + "/" + s.data[index]["tags"]),`

Following is the error:-

`type 'List<dynamic>' is not a subtype of type 'String'
`

When trying to display data from Tags, Categories above error is displayed.

**Comment by samarthagarwal** [comment]
This is not an issue in the package. You are passing a `List` where the `Text` widget expects a `String`. Closing as unrelated.
