### ISSUE TITLE
Compatibility with WooCommerce REST API V3

### ISSUE THREAD

**Issue by michael-attal** [samarthagarwal/woocommerce_dart#14]
It is compatible with the new WooCommerce Rest API V3 ?

**Comment by samarthagarwal** [comment]
It used the V2 API by default. You can change it here: https://github.com/samarthagarwal/woocommerce_dart/blob/master/lib/woocommerce_api.dart#L53

**Comment by michael-attal** [comment]
Thx, I tried and all work as expected.
