### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by thgdigital** [samarthagarwal/woocommerce_dart#2]
Because query_string 1.0.4 requires SDK version >=0.8.10+6 <2.0.0 and no versions of query_string match >1.0.4 <2.0.0, query_string ^1.0.4 is forbidden.
So, because helo_words depends on woocommerce_api ^0.0.3 which depends on query_string ^1.0.4, version solving failed.
pub get failed (1)
exit code 1

**Comment by samarthagarwal** [comment]
Fixed in [dcdba81](https://github.com/samarthagarwal/woocommerce_dart/commit/b8092e68b011c82b9a40d24c87ef2754cf5cf265).
