### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by farisabbasi** [samarthagarwal/woocommerce_dart#3]
I copied your code but my app is stuck on Loading text its not fetching products

here's my code

`import 'dart:async';

import 'package:flutter/material.dart';
import 'package:woocommerce_api/woocommerce_api.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'WooCommerce API Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  List<Widget> products = [];

  Future getProducts() async {

    /// Initialize the API
    WooCommerceAPI wc_api = new WooCommerceAPI(
        "http://localhost/ropaarmario/wp-json/wc/v2/products",
        "ck_87f26757f5b65a28f50b9fb5b460793abb6f1d93",
        "cs_fa87963767fbe06b60fa23da38f31d514c51e2a3"
    );

    /// Get data using the endpoint
    var p = await wc_api.getAsync("products");
    return p;
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: FutureBuilder(
        future: getProducts(),
        builder: (_, s){

          if(s.data == null){
            return Container(
              child: Center(
                child: Text("Loading..."),
              ),
            );
          }

          return ListView.builder(
              itemCount: s.data.length,
              itemBuilder: (_, index){

                /// create a list of products
                return ListTile(
                  leading: CircleAvatar(
                    child: Image.network(s.data[index]["images"][0]["src"]),
                  ),
                  title: Text(s.data[index]["name"]),
                  subtitle: Text("Buy now for \$ " + s.data[index]["price"]),
                );

              }
          );
        },
      ),
    );
  }
}
`
i checked on postman its working through oauth authentication method

**Comment by samarthagarwal** [comment]
Keep your url `http://localhost/ropaarmario` only. No need to append the `wp-json/wc/v2` part.
