### ISSUE TITLE
Still Not Working

### ISSUE THREAD

**Issue by farisabbasi** [samarthagarwal/woocommerce_dart#4]
Still showing the same Loading.. text while my api is working fine on postpan
![Image of Prob](https://preview.ibb.co/g5udJp/Screenshot_1.png)

**Comment by samarthagarwal** [comment]
Share the complete logs.

**Comment by farisabbasi** [comment]
10-09 22:50:28.355 14213-14213/com.frabs.woocommerce I/zygote: Not late-enabling -Xcheck:jni (already on)
10-09 22:50:28.386 14213-14213/com.frabs.woocommerce W/zygote: Unexpected CPU variant for X86 using defaults: x86
10-09 22:50:28.960 14213-14213/com.frabs.woocommerce I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
10-09 22:50:28.968 14213-14213/com.frabs.woocommerce D/EGL_emulation: eglCreateContext: 0xea8b61e0: maj 2 min 0 rcv 2
10-09 22:50:29.210 14213-14236/com.frabs.woocommerce I/flutter: Observatory listening on http://127.0.0.1:58043/
10-09 22:50:29.308 14213-14232/com.frabs.woocommerce D/EGL_emulation: eglMakeCurrent: 0xea8b61e0: ver 2 0 (tinfo 0xcdd03fa0)
10-09 22:50:29.537 14213-14237/com.frabs.woocommerce D/OpenGLRenderer: HWUI GL Pipeline
10-09 22:50:29.570 14213-14237/com.frabs.woocommerce I/OpenGLRenderer: Initialized EGL, version 1.4
10-09 22:50:29.571 14213-14237/com.frabs.woocommerce D/OpenGLRenderer: Swap behavior 1
10-09 22:50:29.573 14213-14237/com.frabs.woocommerce W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
10-09 22:50:29.573 14213-14237/com.frabs.woocommerce D/OpenGLRenderer: Swap behavior 0
10-09 22:50:29.579 14213-14237/com.frabs.woocommerce D/EGL_emulation: eglCreateContext: 0xe2c851e0: maj 2 min 0 rcv 2
10-09 22:50:29.603 14213-14237/com.frabs.woocommerce D/EGL_emulation: eglMakeCurrent: 0xe2c851e0: ver 2 0 (tinfo 0xe2c83490)
10-09 22:50:29.650 14213-14213/com.frabs.woocommerce D/EGL_emulation: eglCreateContext: 0xea8b5ca0: maj 2 min 0 rcv 2
10-09 22:50:29.738 14213-14213/com.frabs.woocommerce D/EGL_emulation: eglMakeCurrent: 0xea8b5ca0: ver 2 0 (tinfo 0xcdd03af0)
10-09 22:50:30.794 14213-14237/com.frabs.woocommerce D/EGL_emulation: eglMakeCurrent: 0xe2c851e0: ver 2 0 (tinfo 0xe2c83490)
10-09 22:50:31.578 14213-14231/com.frabs.woocommerce D/EGL_emulation: eglMakeCurrent: 0xea8b5ca0: ver 2 0 (tinfo 0xe2c833e0)
10-09 22:50:32.811 14213-14213/com.frabs.woocommerce I/Choreographer: Skipped 61 frames!  The application may be doing too much work on its main thread.

**Comment by samarthagarwal** [comment]
The log does not help. It has no information about the network requests. Anyway, I guess your emulator/phone does not have access to the localhost server that your woocommerce is running on.

**Comment by farisabbasi** [comment]
So what is the solution for this? Can you please help me?

**Comment by farisabbasi** [comment]
@samarthagarwal Please solve my issue

**Comment by farisabbasi** [comment]
Solved
