### ISSUE TITLE
The following NoSuchMethodError was thrown during performLayout()

### ISSUE THREAD

**Issue by farisabbasi** [samarthagarwal/woocommerce_dart#5]
Using Exactly Your Code I Got This Error

I/flutter (13726): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13726): The following NoSuchMethodError was thrown during performLayout():
I/flutter (13726): The method '[]' was called on null.
I/flutter (13726): Receiver: null
I/flutter (13726): Tried calling: []("images")
I/flutter (13726): 
I/flutter (13726): When the exception was thrown, this was the stack:
I/flutter (13726): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
I/flutter (13726): #1      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (file:///C:/Projects/flutter/woo_commerce/lib/main.dart:78:55)
I/flutter (13726): #2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:258:20)
I/flutter (13726): #3      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:783:67)
I/flutter (13726): #4      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter (13726): #5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:783:26)
I/flutter (13726): #6      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:796:55)
I/flutter (13726): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
I/flutter (13726): #8      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:789:11)
I/flutter (13726): #9      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter (13726): #10     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1727:58)
I/flutter (13726): #11     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter (13726): #12     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1727:13)
I/flutter (13726): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter (13726): #14     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:321:5)
I/flutter (13726): #15     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
I/flutter (13726): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (13726): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (13726): #20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
I/flutter (13726): #21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
I/flutter (13726): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (13726): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (13726): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (13726): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (13726): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (13726): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (13726): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (13726): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (13726): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1631:7)
I/flutter (13726): #39     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (13726): #40     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
I/flutter (13726): #41     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (13726): #42     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (13726): #43     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1506:7)
I/flutter (13726): #44     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (13726): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (13726): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
I/flutter (13726): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (13726): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13726): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (13726): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (13726): #51     _invoke (dart:ui/hooks.dart:128:13)
I/flutter (13726): #52     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter (13726): 
I/flutter (13726): The following RenderObject was being processed when the exception was fired:
I/flutter (13726):   RenderSliverList#8c35f relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (13726):   creator: SliverList ← MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter (13726):   IgnorePointer-[GlobalKey#4e1f0] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (13726):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#99210] ←
I/flutter (13726):   _ScrollSemantics-[GlobalKey#e1260] ← RepaintBoundary ← ⋯
I/flutter (13726):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter (13726):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (13726):   scrollOffset: 0.0, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection:
I/flutter (13726):   AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 853.4 cacheOrigin: 0.0 )
I/flutter (13726):   geometry: null
I/flutter (13726):   no children current live
I/flutter (13726): This RenderObject has no descendants.
I/flutter (13726): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (13726): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (13726): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (13726): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.

**Comment by samarthagarwal** [comment]
Share more console logs. There must be something of use before these logs that you have posted.
