### ISSUE TITLE
Same error

### ISSUE THREAD

**Issue by danasugu** [samarthagarwal/woocommerce_dart#7]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device Android SDK built for x86...
D/        (23443): HostConnection::get() New Host Connection established 0xe6d70dc0, tid 23472
D/EGL_emulation(23443): eglMakeCurrent: 0xe7226e60: ver 2 0 (tinfo 0xe7250a10)
I/flutter (23443): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23443): The following NoSuchMethodError was thrown building:
I/flutter (23443): The method '[]' was called on null.
I/flutter (23443): Receiver: null
I/flutter (23443): Tried calling: []("images")
I/flutter (23443): 
I/flutter (23443): When the exception was thrown, this was the stack:
I/flutter (23443): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (23443): #1      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:woocom/main.dart:78:55)
I/flutter (23443): #2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:397:15)
I/flutter (23443): #3      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1000:67)
I/flutter (23443): #4      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter (23443): #5      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1000:26)
I/flutter (23443): #6      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1013:55)
I/flutter (23443): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter (23443): #8      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1006:11)
I/flutter (23443): #9      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
I/flutter (23443): #10     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
I/flutter (23443): #11     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
I/flutter (23443): #12     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
I/flutter (23443): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:5)
I/flutter (23443): #14     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:341:5)
I/flutter (23443): #15     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
I/flutter (23443): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (23443): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (23443): #20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter (23443): #21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter (23443): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23443): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23443): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23443): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23443): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23443): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23443): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23443): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23443): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23443): #39     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (23443): #40     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (23443): #41     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (23443): #42     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (23443): #43     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (23443): #44     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (23443): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (23443): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (23443): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (23443): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (23443): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (23443): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (23443): #51     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (23443): #52     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (23443): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by samarthagarwal** [comment]
Your API is not returning data, hence the error.

**Comment by JacquesvanWyk** [comment]
You keep closing the issue but there are no solutions. I have checked my code on Postman and I can run requests and get json back of products but if run code I get the same error as the person above. Something is wrong in your code. Check that error says The method '[]' was called on null. It is not getting anything from api call. Are you using the latest woocommerce api  /wp-json/wc/v3/ in package request?

**Comment by samarthagarwal** [comment]
No, it uses /wp-json/wc/v2/ in all requests. The error message indicates that no data is returned. Share your keys and url with me so I can test with your store.

**Comment by JacquesvanWyk** [comment]
I will send it in an email. Thank you

*UPDATE I have send you an email let me know if you got it.

**Comment by samarthagarwal** [comment]
Yes, @JacquesvanWyk . I got your email and added a fix to the package which has some issues in the parameters for https based websites. Try out version 0.0.7 and let me know if the issue persists.

**Comment by JacquesvanWyk** [comment]
> Yes, @JacquesvanWyk . I got your email and added a fix to the package which has some issues in the parameters for https based websites. Try out version 0.0.7 and let me know if the issue persists.

I tested it and it is working now. Thank you for your help.
